EPL/Controllers/DivisionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EPL.Models;
using EPL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EPL.Controllers
{
    public class DivisionsController : Controller
    {

        private readonly IDivisionRepository divisionRepository;

        [TempData]
        public string message { get; set; }

        public DivisionsController(IDivisionRepository divisionRepository)
        {
            this.divisionRepository = divisionRepository;
        }
        // GET: /<controller>/

        public IActionResult List(DivisionsListViewModel divisionsListViewModel)
        {
            var divisions = divisionRepository.GetDivisionByName(divisionsListViewModel.SearchTerm);

            return View(new DivisionsListViewModel
            {
                Divisions = divisions,
                Message = message
            });
        }

        [Authorize]
        public IActionResult Edit(int? divisionId)
        {
            Division division;
            string header;
            if(!divisionId.HasValue)
            {
                division = new Division();
                header = "Add New";
            }
            else
            {
                division = divisionRepository.GetDivisionById(divisionId.Value);
                header = "Edit";
            }
            if (division == null)
            {
                return NotFound();
            }
            return View(new DivisionsEditViewModel
            {
                Division = division,
                Header = header
            });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(Division division)
        {
            if(division.DivisionId > 0)
            {
                divisionRepository.Update(division);
            }
            else
            {
                divisionRepository.Add(division);
            }
            divisionRepository.Commit();
            TempData["message"] = "Division saved!"; //am I doing the tempdata right by putting at controller? if not, where?
            return RedirectToAction("List");
        }

        [Authorize]
        [HttpPost]
        public IActionResult Delete(int divisionId)
        {
            //to add existing team check in the future
            var division = divisionRepository.Delete(divisionId);
            divisionRepository.Commit();
            if(division == null)
            {
                return NotFound();
            }

            TempData["Message"] = $"{division.Name} deleted.";
            return RedirectToAction("List");

        }
    }
}

EPL/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using EPL.Models;
using EPL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EPL.Controllers
{
	public class PlayersController : Controller
	{
        private readonly IPlayerRepository playerRepository;
        private readonly ITeamRepository teamRepository;
        private readonly IHtmlHelper htmlHelper;

        [TempData]
        public string message { get; set; }

        public PlayersController(IPlayerRepository playerRepository, ITeamRepository teamRepository, IHtmlHelper htmlHelper)
		{
            this.playerRepository = playerRepository;
            this.teamRepository = teamRepository;
            this.htmlHelper = htmlHelper;
        }

        public IActionResult List(PlayersListViewModel playersListViewModel)
        {
            var players = playerRepository.GetPlayersByName(playersListViewModel.SearchTerm);

            return View(new PlayersListViewModel
            {
                Players = players,
                Message = message
            });
        }

        public IActionResult Details(int playerId)
        {
            var player = playerRepository.GetPlayerById(playerId);

            return View(player);
        }

        [Authorize]
        public IActionResult Edit(int? playerId)
        {
            Player player;
            string header;
            IEnumerable<Team> teams = teamRepository.GetTeamsByName(null, null);
            IEnumerable<SelectListItem> positions = htmlHelper.GetEnumSelectList<Position>();

            if(!playerId.HasValue)
            {
                player = new Player();
                header = "Add New";
            }
            else
            {
                player = playerRepository.GetPlayerById(playerId.Value);
                header = "Edit";
            }

            if(player == null)
            {
                return NotFound();
            }

            return View(new PlayersEditViewModel
            {
                Player = player,
                Header = header,
                Teams = teams,
                Positions = positions
            });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(Player player)
        {
            if(player.PlayerId > 0)
            {
                playerRepository.Update(player);
            }
            else
            {
                playerRepository.Add(player);
            }
            playerRepository.Commit();
            TempData["message"] = "Player saved!";
            return RedirectToAction("List");
        }

        [Authorize]
        [HttpPost]
        public IActionResult Delete(int playerId)
        {
            //to add existing player check in the future
            var player = playerRepository.Delete(playerId);
            playerRepository.Commit();
            if (player == null)
            {
                return NotFound();
            }

            TempData["Message"] = $"{player.Name} deleted.";
            return RedirectToAction("List");
        }
    }
}

EPL/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using EPL.Models;
using EPL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace EPL.Controllers
{
	public class TeamsController : Controller
	{
        private readonly ITeamRepository teamRepository;
        private readonly IDivisionRepository divisionRepository;

        [TempData]
        public string message { get; set; }

        public TeamsController(ITeamRepository teamRepository, IDivisionRepository divisionRepository)
		{
            this.teamRepository = teamRepository;
            this.divisionRepository = divisionRepository;
        }

        public IActionResult List(TeamsListViewModel teamsListViewModel, int? divisionId)
        {
            var teams = teamRepository.GetTeamsByName(teamsListViewModel.SearchTerm, divisionId);

            return View(new TeamsListViewModel
            {
                Teams = teams,
                Message = message
            });
        }

        public IActionResult Details(int teamId)
        {
            var team = teamRepository.GetTeamById(teamId);
                
            return View(team);
        }

        [Authorize]
        public IActionResult Edit(int? teamId)
        {
            Team team;
            string header;
            IEnumerable<Division> divisions = divisionRepository.GetDivisionByName(null);

            if(!teamId.HasValue)
            {
                team = new Team();
                header = "Add New";
            }
            else
            {
                team = teamRepository.GetTeamById(teamId.Value);
                header = "Edit";
            }

            if(team == null)
            {
                return NotFound();
            }
            return View(new TeamsEditViewModel
            {
                Team = team,
                Header = header,
                Divisions = divisions
            });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Edit(Team team)
        {
            if(team.TeamId > 0)
            {
                teamRepository.Update(team);
            }
            else
            {
                teamRepository.Add(team);
            }
            teamRepository.Commit();
            TempData["message"] = "Team saved!";
            return RedirectToAction("List");
        }

        [Authorize]
        [HttpPost]
        public IActionResult Delete(int teamId)
        {
            //to add existing player check in the future
            var team = teamRepository.Delete(teamId);
            teamRepository.Commit();
            if(team == null)
            {
                return NotFound();
            }

            TempData["Message"] = $"{team.Name} deleted.";
            return RedirectToAction("List");
        }
    }
}

EPL/Views/Shared/_DeleteModal.cshtml
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete!</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer">
                <form method="post">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

EPL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EPL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EPL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Divisions" asp-action="List">Divisions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="List">Teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="List">Players</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EPL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>